framework:
    messenger:
        # Transport utilisé pour stocker les messages qui échouent après les tentatives de retry
        failure_transport: failed

        transports:
            # Transport asynchrone pour traiter les messages en arrière-plan
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'  # Exemple : doctrine://default ou amqp://localhost
                options:
                    use_notify: true  # Pour PostgreSQL : notifications instantanées (si supportées)
                    check_delayed_interval: 60000  # Vérifie les messages différés toutes les 60 secondes
                retry_strategy:
                    max_retries: 3      # 3 tentatives avant d’échouer définitivement
                    multiplier: 2       # Les délais de retry augmentent de façon exponentielle

            # Transport pour stocker les messages en échec dans la base de données
            failed: 'doctrine://default?queue_name=failed'

            # Transport synchrone désactivé, utile uniquement pour tests ou debug
            # sync: 'sync://'

        default_bus: messenger.bus.default  # Bus de messages utilisé par défaut

        buses:
            messenger.bus.default: []  # Aucun middleware personnalisé ajouté ici

        routing:
            # Ces classes sont routées vers le transport asynchrone (async)

            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async

            # ⚠️ ATTENTION : Ligne ci-dessous à commenter ou supprimer
            # Sinon, erreur : "class or interface 'App\Message\SendEmailMessage' not found"
            #
            # App\Message\SendEmailMessage: async
            #
            # Pour corriger cette erreur :
            # ➤ Soit tu crées la classe App\Message\SendEmailMessage
            # ➤ Soit tu commentes/supprimes cette ligne comme ici

            # Exemple correct si tu veux router un message existant :
            # 'App\Message\YourMessage': async
