security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        chain_provider:
            chain:
                providers: [app_user_provider, app_admin_provider, app_employe_provider]

        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

        app_admin_provider:
            entity:
                class: App\Entity\Admin
                property: email

        app_employe_provider:
            entity:
                class: App\Entity\Employes
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: chain_provider
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: email
                password_parameter: _password
                enable_csrf: true
                default_target_path: redirect_after_login

            logout:
                path: app_logout

    role_hierarchy:  
        ROLE_ADMIN: [ROLE_EMPLOYE, ROLE_USER]
        # ROLE_EMPLOYE: [ROLE_EMPLOYE]
        # ROLE_USER: [ROLE_USER]

    access_control:
        - { path: '^/billets_public', roles: PUBLIC_ACCESS }
        - { path: '^/admin', roles: ROLE_ADMIN }
        - { path: '^/billets', roles: ROLE_ADMIN }
        - { path: '^/user', roles: ROLE_ADMIN }
        # - { path: '^/total_billets', roles: ROLE_ADMIN }
        - { path: '^/ventes', roles: ROLE_ADMIN }
        # - { path: '^/billets_public', roles: ROLE_USER }
        # - { path: '^/employe', roles: ROLE_EMPLOYE }

    access_denied_url: "/access-denied"

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
